<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>aspnet-PROJECT_OTSP-cccc7f55-6652-4421-b6f3-d9216af7ef4d</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>.</DockerfileContext>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.12" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.12" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.12" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12" PrivateAssets="all" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Areas\Admin\" />
	  <Folder Include="Areas\Tutor\" />
	  <Folder Include="Areas\Student_Parent\" />
	  <Folder Include="Data\Migrations\" />
	  <Folder Include="Dtos\" />
	  <Folder Include="Services\" />
	</ItemGroup>

</Project>